locations_data = {
    "start": {"description": "Вы стоите на перекрестке выбора... Куда вы хотите пойти?\n1) В низу\n2) В сверху\n3)пойду как я погуглю чё это такое ваше IT",
                "options": {"1": "backend", "2": "frontend", "3": "google"},
                "pucture": "pictures/crossroad.jpg"},
    "forest": {"description": "Вы решились выбрать низ\n1) учится дальше\n2) Вернуться на перекресток",
                "options": {"1": "deep_backend", "2": "start"},
               "pucture": "pictures/forest.jpg"},
    "deep_forest": {"description": "кажется вы  задумались о чём то\n1)я продолжу дальше учится! \n2) я подумаю...",
                    "options": {"1": "find_path", "2": "backend"},
                    "pucture": "pictures/forest.jpg"},
    "find_path": {"description": "Поздравляю, вы смогли повысить свой  ранг до backend Middle!",
                  "options": {},
                  "pucture": "pictures/win.jpg"},
    "mountains": {"description": "Вы решились выбрать frontend\n1)мне нравится:)\n2)скучно пойду кибер безопасность изучать:)\n3) Вернуться на перекресток",
                    "options": {"1": "kaif", "2": "wasted", "3": "start"},
                    "pucture": "pictures/mountains.jpg"},
    "waterfall": {"description": "Вы почти смогли освоить Junior!. Ваши действия?\n1) продолжу обучение:)\n2) не моё:(",
                    "options": {"1": "approach_kaif", "2": "frontend"},
                    "pucture": "pictures/waterfall.jpg"},
    "approach_waterfall": {"description": "УРА вы смогли стать frontend Middle",
                            "options": {},
                            "pucture": "pictures/win.jpg"},
    "cave": {"description": "Вы думаете что то как то надоело IT...\n1) устал...\n2) нене на двух стулов сидеть не буду!",
            "options": {"1": "explore_wasted", "2": "frontend"},
            "pucture": "pictures/cave.jpg"},
    "explore_cave": {"description": "УВЫ вы забили на всё навыки потеренены апатия выгорания...!",
                    "options": {},
                    "pucture": "pictures/bear.jpg"},
    "village": {"description": "Вы начали читать новости...\n1) ну ка почитаем\n2) я подумаю о своём выборе",
                "options": {"1": "talk_to_google", "2": "start"},
                "pucture": "pictures/village.jpg"},
    "talk_to_villagers": {"description": "аааа ужас IT рынок рушится програмисты не востребованы теперь их заменит искусственный интелект! :| не шпасиба пойду скачивать взломанный сбербанк и  обузить темки... ",
        "options": {},
        "pucture": "pictures/villager.jpg"}
}